POST http://localhost:8000/api/v1/order
Content-Type: application/json

{
"menuItems": [
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "quantity": 1
  },
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66af45",
    "quantity": 1
  }
]
}

###
GET http://localhost:8000/api/v1/order/d290f1ee-6c54-4b01-90E6-d701748fo851

###
DELETE http://localhost:8000/api/v1/order/49313bc6-37fd-43a6-8cc5-d7216feb2a41

###
POST http://localhost:8000/api/v1/order/8ae54fa9-728c-4de6-985d-8317db86fb2b
Content-Type: application/json

{
  "menuItems": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afbbb",
      "quantity": 30
    },
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66a111",
      "quantity": 30
    }
  ]
}