POST http://localhost:8000/api/v1/order
Content-Type: application/json

{
"menuItems": [
  {
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "quantity": 1
  },
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66af45",
    "quantity": 1
  }
]
}

###
GET http://localhost:8000/api/v1/orders
###
DELETE http://localhost:8000/api/v1/order/0b199551-f6ba-46d4-9f16-cc30bfaf2b81
